spring:
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 6000
# log
logging:
  file: ./logs/java.log
  level:
    root: ERROR