server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # false 表明该应用是一个 eureka server
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  application:
    name: server-eurka
  security:
    user:
      name: admin # Security 用户名和密码
      password: admin
